// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mix_gaussian_grad_cpp
arma::vec mix_gaussian_grad_cpp(const arma::vec& x, const arma::mat& x_star, const List& params, const IntegerVector& exclude);
RcppExport SEXP _LangevinAnimalTracking_mix_gaussian_grad_cpp(SEXP xSEXP, SEXP x_starSEXP, SEXP paramsSEXP, SEXP excludeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x_star(x_starSEXP);
    Rcpp::traits::input_parameter< const List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type exclude(excludeSEXP);
    rcpp_result_gen = Rcpp::wrap(mix_gaussian_grad_cpp(x, x_star, params, exclude));
    return rcpp_result_gen;
END_RCPP
}
// solve_ODE_cpp
arma::vec solve_ODE_cpp(const arma::vec& U, double delta, const arma::vec& push, const List& potential_params, Nullable<int> ind_fixed_point);
RcppExport SEXP _LangevinAnimalTracking_solve_ODE_cpp(SEXP USEXP, SEXP deltaSEXP, SEXP pushSEXP, SEXP potential_paramsSEXP, SEXP ind_fixed_pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type U(USEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type push(pushSEXP);
    Rcpp::traits::input_parameter< const List& >::type potential_params(potential_paramsSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type ind_fixed_point(ind_fixed_pointSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_ODE_cpp(U, delta, push, potential_params, ind_fixed_point));
    return rcpp_result_gen;
END_RCPP
}
// log_dmvnorm_chol_cpp
double log_dmvnorm_chol_cpp(const arma::vec& x, const arma::vec& mean, const arma::mat& cholSigma);
RcppExport SEXP _LangevinAnimalTracking_log_dmvnorm_chol_cpp(SEXP xSEXP, SEXP meanSEXP, SEXP cholSigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cholSigma(cholSigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_dmvnorm_chol_cpp(x, mean, cholSigma));
    return rcpp_result_gen;
END_RCPP
}
// product_gaussian_cpp
List product_gaussian_cpp(const arma::mat& P1, const arma::mat& P2, const arma::vec& mean1, const arma::vec& mean2, const arma::mat& M);
RcppExport SEXP _LangevinAnimalTracking_product_gaussian_cpp(SEXP P1SEXP, SEXP P2SEXP, SEXP mean1SEXP, SEXP mean2SEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type P1(P1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P2(P2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mean1(mean1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mean2(mean2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(product_gaussian_cpp(P1, P2, mean1, mean2, M));
    return rcpp_result_gen;
END_RCPP
}
// chol_cpp
arma::mat chol_cpp(const arma::mat& Q);
RcppExport SEXP _LangevinAnimalTracking_chol_cpp(SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(chol_cpp(Q));
    return rcpp_result_gen;
END_RCPP
}
// chol2inv_cpp
arma::mat chol2inv_cpp(const arma::mat& R);
RcppExport SEXP _LangevinAnimalTracking_chol2inv_cpp(SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(chol2inv_cpp(R));
    return rcpp_result_gen;
END_RCPP
}
// choose_center_cpp
int choose_center_cpp(const arma::vec& x, const arma::mat& x_star, const List& params);
RcppExport SEXP _LangevinAnimalTracking_choose_center_cpp(SEXP xSEXP, SEXP x_starSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x_star(x_starSEXP);
    Rcpp::traits::input_parameter< const List& >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(choose_center_cpp(x, x_star, params));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LangevinAnimalTracking_mix_gaussian_grad_cpp", (DL_FUNC) &_LangevinAnimalTracking_mix_gaussian_grad_cpp, 4},
    {"_LangevinAnimalTracking_solve_ODE_cpp", (DL_FUNC) &_LangevinAnimalTracking_solve_ODE_cpp, 5},
    {"_LangevinAnimalTracking_log_dmvnorm_chol_cpp", (DL_FUNC) &_LangevinAnimalTracking_log_dmvnorm_chol_cpp, 3},
    {"_LangevinAnimalTracking_product_gaussian_cpp", (DL_FUNC) &_LangevinAnimalTracking_product_gaussian_cpp, 5},
    {"_LangevinAnimalTracking_chol_cpp", (DL_FUNC) &_LangevinAnimalTracking_chol_cpp, 1},
    {"_LangevinAnimalTracking_chol2inv_cpp", (DL_FUNC) &_LangevinAnimalTracking_chol2inv_cpp, 1},
    {"_LangevinAnimalTracking_choose_center_cpp", (DL_FUNC) &_LangevinAnimalTracking_choose_center_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_LangevinAnimalTracking(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
