# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mix_gaussian_grad_cpp <- function(x, x_star, params, exclude) {
    .Call('_LangevinAnimalTracking_mix_gaussian_grad_cpp', PACKAGE = 'LangevinAnimalTracking', x, x_star, params, exclude)
}

solve_ODE_cpp <- function(U, delta, push, potential_params, ind_fixed_point = NULL) {
    .Call('_LangevinAnimalTracking_solve_ODE_cpp', PACKAGE = 'LangevinAnimalTracking', U, delta, push, potential_params, ind_fixed_point)
}

log_dmvnorm_chol_cpp <- function(x, mean, cholSigma) {
    .Call('_LangevinAnimalTracking_log_dmvnorm_chol_cpp', PACKAGE = 'LangevinAnimalTracking', x, mean, cholSigma)
}

product_gaussian_cpp <- function(P1, P2, mean1, mean2, M) {
    .Call('_LangevinAnimalTracking_product_gaussian_cpp', PACKAGE = 'LangevinAnimalTracking', P1, P2, mean1, mean2, M)
}

chol_cpp <- function(Q) {
    .Call('_LangevinAnimalTracking_chol_cpp', PACKAGE = 'LangevinAnimalTracking', Q)
}

chol2inv_cpp <- function(R) {
    .Call('_LangevinAnimalTracking_chol2inv_cpp', PACKAGE = 'LangevinAnimalTracking', R)
}

choose_center_cpp <- function(x, x_star, params) {
    .Call('_LangevinAnimalTracking_choose_center_cpp', PACKAGE = 'LangevinAnimalTracking', x, x_star, params)
}

